#!/usr/bin/env bash

get_subdomain_info() {
    local domain=$1
    local subdomain=$2
    local full_domain="${subdomain}.${domain}"
    
    # shellcheck disable=SC2086
    local dig_result=$(dig $full_domain)
    
    local destination=$(echo "$dig_result" | awk '/^[^;]/ && /'"$full_domain"'.*IN.*A/ {print $NF}')
    local record_type=$(echo "$dig_result" | awk '/^[^;]/ && /'"$full_domain"'.*IN/ {print $(NF-1)}')
    
    if [ -z "$record_type" ]; then
        record_type="A"
    fi
    
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
else
    get_subdomain_info "$domain" "$subdomain"
fi